///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyNeoloadTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("7eb37bc5-3d72-4d3c-982a-d00ae222d57e", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyNeoloadTestRepository repository.
        /// </summary>
        public static MyNeoloadTestRepository repo = MyNeoloadTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            ignore_certificate_errors = "--ignore-certificate-errors";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _ignore_certificate_errors;

        /// <summary>
        /// Gets or sets the value of variable ignore_certificate_errors.
        /// </summary>
        [TestVariable("0f19a404-8d7f-4ff3-82fd-02c16d57193a")]
        public string ignore_certificate_errors
        {
            get { return _ignore_certificate_errors; }
            set { _ignore_certificate_errors = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("home");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://preprod-neoload.saas.neotys.com/' with browser 'Chrome' in normal mode (with arguments --ignore-certificate-errors).", new RecordItemIndex(1));
            Host.Current.OpenBrowser("https://preprod-neoload.saas.neotys.com/", "Chrome", ignore_certificate_errors, false, false, false, true, false);
            Delay.Milliseconds(0);
            
            //Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("home");
            //Delay.Milliseconds(0);
            
            //Ranorex.NeoLoad.NeoLoadCodeCollection.SendTimingValues(repo.PreprodNeoloadSaasNeotysComGoogle.ChromeInfo, "home");
            //Delay.Milliseconds(0);
            
            //Ranorex.NeoLoad.NeoLoadCodeCollection.StopTransaction();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'NeoLoadWeb.LoginUsername'", repo.NeoLoadWeb.LoginUsernameInfo, new ActionTimeout(5000), new RecordItemIndex(6));
            repo.NeoLoadWeb.LoginUsernameInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'anakin'.", new RecordItemIndex(7));
            Keyboard.Press("anakin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 905;482.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(8));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("905;482");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'NeoLoadWebGoogleChrome'.", repo.NeoLoadWebGoogleChrome.SelfInfo, new RecordItemIndex(9));
            repo.NeoLoadWebGoogleChrome.Self.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 983;598.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(10));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("983;598");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 969;570.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(11));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("969;570");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 75;249.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(12));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("75;249");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 79;903.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(13));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("79;903");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWebGoogleChrome.Element1228856752' at 221;431.", repo.NeoLoadWebGoogleChrome.Element1228856752Info, new RecordItemIndex(14));
            repo.NeoLoadWebGoogleChrome.Element1228856752.Click("221;431");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
