///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyNeoloadTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The simple_record recording.
    /// </summary>
    [TestModule("a645a157-ef64-4983-8fa1-d7e145fba24b", ModuleType.Recording, 1)]
    public partial class Simple_record : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyNeoloadTestRepository repository.
        /// </summary>
        public static MyNeoloadTestRepository repo = MyNeoloadTestRepository.Instance;

        static Simple_record instance = new Simple_record();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Simple_record()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Simple_record Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://ushahidi.demo.neotys.com' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://ushahidi.demo.neotys.com", "chrome", "", false, false, false, true, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWeb.Client' at 829;246.", repo.NeoLoadWeb.ClientInfo, new RecordItemIndex(1));
            repo.NeoLoadWeb.Client.Click("829;246");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
