///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyNeoloadTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The transaction_record recording.
    /// </summary>
    [TestModule("c761e308-8719-4555-8c3c-df21817a2bb1", ModuleType.Recording, 1)]
    public partial class Transaction_record : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyNeoloadTestRepository repository.
        /// </summary>
        public static MyNeoloadTestRepository repo = MyNeoloadTestRepository.Instance;

        static Transaction_record instance = new Transaction_record();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Transaction_record()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Transaction_record Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("Home");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://ushahidi.demo.neotys.com' with browser 'IE' in normal mode.", new RecordItemIndex(1));
            Host.Current.OpenBrowser("http://ushahidi.demo.neotys.com", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("Reports");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWeb.Mainmenu.Reports' at 51;16.", repo.NeoLoadWeb.Mainmenu.ReportsInfo, new RecordItemIndex(3));
            repo.NeoLoadWeb.Mainmenu.Reports.Click("51;16");
            Delay.Milliseconds(200);
            
            Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("Submit Report");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWeb.Mainmenu.SubmitAReport' at 92;14.", repo.NeoLoadWeb.Mainmenu.SubmitAReportInfo, new RecordItemIndex(5));
            repo.NeoLoadWeb.Mainmenu.SubmitAReport.Click("92;14");
            Delay.Milliseconds(200);
            
            Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("Get Alerts");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWeb.Mainmenu.GetAlerts' at 52;18.", repo.NeoLoadWeb.Mainmenu.GetAlertsInfo, new RecordItemIndex(7));
            repo.NeoLoadWeb.Mainmenu.GetAlerts.Click("52;18");
            Delay.Milliseconds(200);
            
            //Ranorex.NeoLoad.NeoLoadCodeCollection.StartTransaction("Back Home");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NeoLoadWeb.BackToHome' at 35;4.", repo.NeoLoadWeb.BackToHomeInfo, new RecordItemIndex(9));
            //repo.NeoLoadWeb.BackToHome.Click("35;4");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
