///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyNeoloadTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyNeoloadTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("7fac3fb8-5dbd-4a96-9ccc-77574879612a")]
    public partial class MyNeoloadTestRepository : RepoGenBaseFolder
    {
        static MyNeoloadTestRepository instance = new MyNeoloadTestRepository();
        MyNeoloadTestRepositoryFolders.NeoLoadWebAppFolder _neoloadweb;
        MyNeoloadTestRepositoryFolders.NeoLoadWebMozillaFirefoxAppFolder _neoloadwebmozillafirefox;
        MyNeoloadTestRepositoryFolders.PreprodNeoloadSaasNeotysComGoogleAppFolder _preprodneoloadsaasneotyscomgoogle;
        MyNeoloadTestRepositoryFolders.ChromeAppFolder _chrome;
        MyNeoloadTestRepositoryFolders.NeoLoadWebGoogleChromeAppFolder _neoloadwebgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the MyNeoloadTestRepository element repository.
        /// </summary>
        [RepositoryFolder("7fac3fb8-5dbd-4a96-9ccc-77574879612a")]
        public static MyNeoloadTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyNeoloadTestRepository() 
            : base("MyNeoloadTestRepository", "/", null, 0, false, "7fac3fb8-5dbd-4a96-9ccc-77574879612a", ".\\RepositoryImages\\MyNeoloadTestRepository7fac3fb8.rximgres")
        {
            _neoloadweb = new MyNeoloadTestRepositoryFolders.NeoLoadWebAppFolder(this);
            _neoloadwebmozillafirefox = new MyNeoloadTestRepositoryFolders.NeoLoadWebMozillaFirefoxAppFolder(this);
            _preprodneoloadsaasneotyscomgoogle = new MyNeoloadTestRepositoryFolders.PreprodNeoloadSaasNeotysComGoogleAppFolder(this);
            _chrome = new MyNeoloadTestRepositoryFolders.ChromeAppFolder(this);
            _neoloadwebgooglechrome = new MyNeoloadTestRepositoryFolders.NeoLoadWebGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7fac3fb8-5dbd-4a96-9ccc-77574879612a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NeoLoadWeb folder.
        /// </summary>
        [RepositoryFolder("33c6da6a-04f7-4be1-b969-9ce7ffd3d2b9")]
        public virtual MyNeoloadTestRepositoryFolders.NeoLoadWebAppFolder NeoLoadWeb
        {
            get { return _neoloadweb; }
        }

        /// <summary>
        /// The NeoLoadWebMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("a04d09bf-5d37-4610-9470-b86400976b0b")]
        public virtual MyNeoloadTestRepositoryFolders.NeoLoadWebMozillaFirefoxAppFolder NeoLoadWebMozillaFirefox
        {
            get { return _neoloadwebmozillafirefox; }
        }

        /// <summary>
        /// The PreprodNeoloadSaasNeotysComGoogle folder.
        /// </summary>
        [RepositoryFolder("ec25c807-4791-4b9d-8597-88f0ee3de2e2")]
        public virtual MyNeoloadTestRepositoryFolders.PreprodNeoloadSaasNeotysComGoogleAppFolder PreprodNeoloadSaasNeotysComGoogle
        {
            get { return _preprodneoloadsaasneotyscomgoogle; }
        }

        /// <summary>
        /// The Chrome folder.
        /// </summary>
        [RepositoryFolder("71f36c83-b26c-44e6-8c69-ef58ed038a19")]
        public virtual MyNeoloadTestRepositoryFolders.ChromeAppFolder Chrome
        {
            get { return _chrome; }
        }

        /// <summary>
        /// The NeoLoadWebGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("aacf8add-2dd9-4682-9954-9bcf7f59afd8")]
        public virtual MyNeoloadTestRepositoryFolders.NeoLoadWebGoogleChromeAppFolder NeoLoadWebGoogleChrome
        {
            get { return _neoloadwebgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class MyNeoloadTestRepositoryFolders
    {
        /// <summary>
        /// The NeoLoadWebAppFolder folder.
        /// </summary>
        [RepositoryFolder("33c6da6a-04f7-4be1-b969-9ce7ffd3d2b9")]
        public partial class NeoLoadWebAppFolder : RepoGenBaseFolder
        {
            MyNeoloadTestRepositoryFolders.MainmenuFolder _mainmenu;
            RepoItemInfo _loginusernameInfo;
            RepoItemInfo _loginloginbuttonInfo;
            RepoItemInfo _jedi1Info;
            RepoItemInfo _dashboardInfo;
            RepoItemInfo _runatestInfo;
            RepoItemInfo _loginpasswordInfo;
            RepoItemInfo _rd1Info;
            RepoItemInfo _searchInfo;
            RepoItemInfo _trendsInfo;
            RepoItemInfo _httpspreprodneoloadsaasneotyscomInfo;
            RepoItemInfo _usersInfo;
            RepoItemInfo _somelabeltagInfo;
            RepoItemInfo _lstibInfo;
            RepoItemInfo _testwikipediaInfo;
            RepoItemInfo _clientInfo;
            RepoItemInfo _backtohomeInfo;

            /// <summary>
            /// Creates a new NeoLoadWeb  folder.
            /// </summary>
            public NeoLoadWebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NeoLoadWeb", "//", parentFolder, 30000, null, false, "33c6da6a-04f7-4be1-b969-9ce7ffd3d2b9", "")
            {
                _mainmenu = new MyNeoloadTestRepositoryFolders.MainmenuFolder(this);
                _loginusernameInfo = new RepoItemInfo(this, "LoginUsername", "input[@id='login-username']", 30000, null, "b87c63db-c368-44ab-905b-fc8fa063b122");
                _loginloginbuttonInfo = new RepoItemInfo(this, "LoginLoginButton", "div[#'login-login-button']", 30000, null, "ee25fa9b-dfcd-41f7-b40e-dbc8c679e7c5");
                _jedi1Info = new RepoItemInfo(this, "Jedi1", "div[#'Jedi1']", 30000, null, "29824395-1cdf-4289-a942-b1db16916c88");
                _dashboardInfo = new RepoItemInfo(this, "Dashboard", ".//div[#'menu-item-dashboard']//span[@innertext='Dashboard']", 30000, null, "865e2df7-43cf-439c-b227-569317befc6a");
                _runatestInfo = new RepoItemInfo(this, "RunATest", ".//div[#'menu-item-runtime']//span[@innertext='Run a Test']", 30000, null, "6fddf2e2-e4bf-4e60-bdab-2dfc64aa9986");
                _loginpasswordInfo = new RepoItemInfo(this, "LoginPassword", ".//input[#'login-password']", 30000, null, "0225b8a2-4eb2-4481-abc5-26c97b6f62d2");
                _rd1Info = new RepoItemInfo(this, "RD1", ".//div[#'R&D1']", 30000, null, "e4b0edad-3975-4412-ab25-8cc3687cfbba");
                _searchInfo = new RepoItemInfo(this, "Search", ".//div[#'menu-item-search']//span[@innertext='Search']", 30000, null, "74c6871e-d57d-4f1d-b12c-6d938b8ca38f");
                _trendsInfo = new RepoItemInfo(this, "Trends", ".//div[#'menu-item-trend']//span[@innertext='Trends']", 30000, null, "9700b51b-59cc-4c32-a4f7-e8d60b6577f9");
                _httpspreprodneoloadsaasneotyscomInfo = new RepoItemInfo(this, "HttpsPreprodNeoloadSaasNeotysCom", ".//div[#'menu-item-trend']/a[@href~'^https://preprod-neoload\\.s']", 30000, null, "a3844a56-2cde-4daf-837e-b74446a98e97");
                _usersInfo = new RepoItemInfo(this, "Users", ".//div[#'menu-item-users']//span[@innertext='Users']", 30000, null, "d7579761-ad7e-4558-bdef-914732f4b4a9");
                _somelabeltagInfo = new RepoItemInfo(this, "SomeLabelTag", ".//div[#'grid']/?/?/table/tbody/tr[5]//label", 30000, null, "a2738353-8b10-4fc8-8c5e-36ea35adfa9f");
                _lstibInfo = new RepoItemInfo(this, "LstIb", ".//input[#'lst-ib']", 30000, null, "fd03c7df-524f-44ce-9c60-51a76ff983ab");
                _testwikipediaInfo = new RepoItemInfo(this, "TestWikipedia", ".//div[#'rso']/div/div/div[1]//h3/a[@innertext='Test - Wikipedia']", 30000, null, "e61f3148-7e93-43c4-8156-b0ca5279bdb2");
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename~'^Neotys\\ Ushahidi\\ -\\ Google\\ ']/container/container[1]", 30000, null, "4df0da61-792a-49fc-b5df-e1bf05fcb461");
                _backtohomeInfo = new RepoItemInfo(this, "BackToHome", ".//div[#'content']/a[@innertext='Back to Home']", 30000, null, "1ec915f8-6546-4d59-96c3-a4094d669ca6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33c6da6a-04f7-4be1-b969-9ce7ffd3d2b9")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33c6da6a-04f7-4be1-b969-9ce7ffd3d2b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginUsername item.
            /// </summary>
            [RepositoryItem("b87c63db-c368-44ab-905b-fc8fa063b122")]
            public virtual Ranorex.InputTag LoginUsername
            {
                get
                {
                    return _loginusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginUsername item info.
            /// </summary>
            [RepositoryItemInfo("b87c63db-c368-44ab-905b-fc8fa063b122")]
            public virtual RepoItemInfo LoginUsernameInfo
            {
                get
                {
                    return _loginusernameInfo;
                }
            }

            /// <summary>
            /// The LoginLoginButton item.
            /// </summary>
            [RepositoryItem("ee25fa9b-dfcd-41f7-b40e-dbc8c679e7c5")]
            public virtual Ranorex.DivTag LoginLoginButton
            {
                get
                {
                    return _loginloginbuttonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginLoginButton item info.
            /// </summary>
            [RepositoryItemInfo("ee25fa9b-dfcd-41f7-b40e-dbc8c679e7c5")]
            public virtual RepoItemInfo LoginLoginButtonInfo
            {
                get
                {
                    return _loginloginbuttonInfo;
                }
            }

            /// <summary>
            /// The Jedi1 item.
            /// </summary>
            [RepositoryItem("29824395-1cdf-4289-a942-b1db16916c88")]
            public virtual Ranorex.DivTag Jedi1
            {
                get
                {
                    return _jedi1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Jedi1 item info.
            /// </summary>
            [RepositoryItemInfo("29824395-1cdf-4289-a942-b1db16916c88")]
            public virtual RepoItemInfo Jedi1Info
            {
                get
                {
                    return _jedi1Info;
                }
            }

            /// <summary>
            /// The Dashboard item.
            /// </summary>
            [RepositoryItem("865e2df7-43cf-439c-b227-569317befc6a")]
            public virtual Ranorex.SpanTag Dashboard
            {
                get
                {
                    return _dashboardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Dashboard item info.
            /// </summary>
            [RepositoryItemInfo("865e2df7-43cf-439c-b227-569317befc6a")]
            public virtual RepoItemInfo DashboardInfo
            {
                get
                {
                    return _dashboardInfo;
                }
            }

            /// <summary>
            /// The RunATest item.
            /// </summary>
            [RepositoryItem("6fddf2e2-e4bf-4e60-bdab-2dfc64aa9986")]
            public virtual Ranorex.SpanTag RunATest
            {
                get
                {
                    return _runatestInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RunATest item info.
            /// </summary>
            [RepositoryItemInfo("6fddf2e2-e4bf-4e60-bdab-2dfc64aa9986")]
            public virtual RepoItemInfo RunATestInfo
            {
                get
                {
                    return _runatestInfo;
                }
            }

            /// <summary>
            /// The LoginPassword item.
            /// </summary>
            [RepositoryItem("0225b8a2-4eb2-4481-abc5-26c97b6f62d2")]
            public virtual Ranorex.InputTag LoginPassword
            {
                get
                {
                    return _loginpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPassword item info.
            /// </summary>
            [RepositoryItemInfo("0225b8a2-4eb2-4481-abc5-26c97b6f62d2")]
            public virtual RepoItemInfo LoginPasswordInfo
            {
                get
                {
                    return _loginpasswordInfo;
                }
            }

            /// <summary>
            /// The RD1 item.
            /// </summary>
            [RepositoryItem("e4b0edad-3975-4412-ab25-8cc3687cfbba")]
            public virtual Ranorex.DivTag RD1
            {
                get
                {
                    return _rd1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RD1 item info.
            /// </summary>
            [RepositoryItemInfo("e4b0edad-3975-4412-ab25-8cc3687cfbba")]
            public virtual RepoItemInfo RD1Info
            {
                get
                {
                    return _rd1Info;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("74c6871e-d57d-4f1d-b12c-6d938b8ca38f")]
            public virtual Ranorex.SpanTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("74c6871e-d57d-4f1d-b12c-6d938b8ca38f")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Trends item.
            /// </summary>
            [RepositoryItem("9700b51b-59cc-4c32-a4f7-e8d60b6577f9")]
            public virtual Ranorex.SpanTag Trends
            {
                get
                {
                    return _trendsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Trends item info.
            /// </summary>
            [RepositoryItemInfo("9700b51b-59cc-4c32-a4f7-e8d60b6577f9")]
            public virtual RepoItemInfo TrendsInfo
            {
                get
                {
                    return _trendsInfo;
                }
            }

            /// <summary>
            /// The HttpsPreprodNeoloadSaasNeotysCom item.
            /// </summary>
            [RepositoryItem("a3844a56-2cde-4daf-837e-b74446a98e97")]
            public virtual Ranorex.ATag HttpsPreprodNeoloadSaasNeotysCom
            {
                get
                {
                    return _httpspreprodneoloadsaasneotyscomInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsPreprodNeoloadSaasNeotysCom item info.
            /// </summary>
            [RepositoryItemInfo("a3844a56-2cde-4daf-837e-b74446a98e97")]
            public virtual RepoItemInfo HttpsPreprodNeoloadSaasNeotysComInfo
            {
                get
                {
                    return _httpspreprodneoloadsaasneotyscomInfo;
                }
            }

            /// <summary>
            /// The Users item.
            /// </summary>
            [RepositoryItem("d7579761-ad7e-4558-bdef-914732f4b4a9")]
            public virtual Ranorex.SpanTag Users
            {
                get
                {
                    return _usersInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Users item info.
            /// </summary>
            [RepositoryItemInfo("d7579761-ad7e-4558-bdef-914732f4b4a9")]
            public virtual RepoItemInfo UsersInfo
            {
                get
                {
                    return _usersInfo;
                }
            }

            /// <summary>
            /// The SomeLabelTag item.
            /// </summary>
            [RepositoryItem("a2738353-8b10-4fc8-8c5e-36ea35adfa9f")]
            public virtual Ranorex.LabelTag SomeLabelTag
            {
                get
                {
                    return _somelabeltagInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The SomeLabelTag item info.
            /// </summary>
            [RepositoryItemInfo("a2738353-8b10-4fc8-8c5e-36ea35adfa9f")]
            public virtual RepoItemInfo SomeLabelTagInfo
            {
                get
                {
                    return _somelabeltagInfo;
                }
            }

            /// <summary>
            /// The LstIb item.
            /// </summary>
            [RepositoryItem("fd03c7df-524f-44ce-9c60-51a76ff983ab")]
            public virtual Ranorex.InputTag LstIb
            {
                get
                {
                    return _lstibInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LstIb item info.
            /// </summary>
            [RepositoryItemInfo("fd03c7df-524f-44ce-9c60-51a76ff983ab")]
            public virtual RepoItemInfo LstIbInfo
            {
                get
                {
                    return _lstibInfo;
                }
            }

            /// <summary>
            /// The TestWikipedia item.
            /// </summary>
            [RepositoryItem("e61f3148-7e93-43c4-8156-b0ca5279bdb2")]
            public virtual Ranorex.ATag TestWikipedia
            {
                get
                {
                    return _testwikipediaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestWikipedia item info.
            /// </summary>
            [RepositoryItemInfo("e61f3148-7e93-43c4-8156-b0ca5279bdb2")]
            public virtual RepoItemInfo TestWikipediaInfo
            {
                get
                {
                    return _testwikipediaInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("4df0da61-792a-49fc-b5df-e1bf05fcb461")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("4df0da61-792a-49fc-b5df-e1bf05fcb461")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }

            /// <summary>
            /// The BackToHome item.
            /// </summary>
            [RepositoryItem("1ec915f8-6546-4d59-96c3-a4094d669ca6")]
            public virtual Ranorex.ATag BackToHome
            {
                get
                {
                    return _backtohomeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BackToHome item info.
            /// </summary>
            [RepositoryItemInfo("1ec915f8-6546-4d59-96c3-a4094d669ca6")]
            public virtual RepoItemInfo BackToHomeInfo
            {
                get
                {
                    return _backtohomeInfo;
                }
            }

            /// <summary>
            /// The Mainmenu folder.
            /// </summary>
            [RepositoryFolder("bcbc16ca-41c7-4f5b-b0e2-7ca9f8ecb639")]
            public virtual MyNeoloadTestRepositoryFolders.MainmenuFolder Mainmenu
            {
                get { return _mainmenu; }
            }
        }

        /// <summary>
        /// The MainmenuFolder folder.
        /// </summary>
        [RepositoryFolder("bcbc16ca-41c7-4f5b-b0e2-7ca9f8ecb639")]
        public partial class MainmenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _getalertsInfo;
            RepoItemInfo _reportsInfo;
            RepoItemInfo _submitareportInfo;

            /// <summary>
            /// Creates a new Mainmenu  folder.
            /// </summary>
            public MainmenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Mainmenu", ".//div[#'mainmenu']", parentFolder, 30000, null, false, "bcbc16ca-41c7-4f5b-b0e2-7ca9f8ecb639", "")
            {
                _getalertsInfo = new RepoItemInfo(this, "GetAlerts", ".//a[@innertext='Get Alerts']", 30000, null, "e84a8c6f-60bb-48b9-8103-a246172fa1d9");
                _reportsInfo = new RepoItemInfo(this, "Reports", ".//a[@innertext='Reports']", 30000, null, "4eff1600-3054-4d11-b030-cd28cbbef8d6");
                _submitareportInfo = new RepoItemInfo(this, "SubmitAReport", ".//a[@innertext='Submit a Report']", 30000, null, "53ba05d0-54dd-47fd-9698-78dfc2a511eb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bcbc16ca-41c7-4f5b-b0e2-7ca9f8ecb639")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bcbc16ca-41c7-4f5b-b0e2-7ca9f8ecb639")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GetAlerts item.
            /// </summary>
            [RepositoryItem("e84a8c6f-60bb-48b9-8103-a246172fa1d9")]
            public virtual Ranorex.ATag GetAlerts
            {
                get
                {
                    return _getalertsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GetAlerts item info.
            /// </summary>
            [RepositoryItemInfo("e84a8c6f-60bb-48b9-8103-a246172fa1d9")]
            public virtual RepoItemInfo GetAlertsInfo
            {
                get
                {
                    return _getalertsInfo;
                }
            }

            /// <summary>
            /// The Reports item.
            /// </summary>
            [RepositoryItem("4eff1600-3054-4d11-b030-cd28cbbef8d6")]
            public virtual Ranorex.ATag Reports
            {
                get
                {
                    return _reportsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Reports item info.
            /// </summary>
            [RepositoryItemInfo("4eff1600-3054-4d11-b030-cd28cbbef8d6")]
            public virtual RepoItemInfo ReportsInfo
            {
                get
                {
                    return _reportsInfo;
                }
            }

            /// <summary>
            /// The SubmitAReport item.
            /// </summary>
            [RepositoryItem("53ba05d0-54dd-47fd-9698-78dfc2a511eb")]
            public virtual Ranorex.ATag SubmitAReport
            {
                get
                {
                    return _submitareportInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SubmitAReport item info.
            /// </summary>
            [RepositoryItemInfo("53ba05d0-54dd-47fd-9698-78dfc2a511eb")]
            public virtual RepoItemInfo SubmitAReportInfo
            {
                get
                {
                    return _submitareportInfo;
                }
            }
        }

        /// <summary>
        /// The NeoLoadWebMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("a04d09bf-5d37-4610-9470-b86400976b0b")]
        public partial class NeoLoadWebMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            MyNeoloadTestRepositoryFolders.PropertyPageFolder _propertypage;

            /// <summary>
            /// Creates a new NeoLoadWebMozillaFirefox  folder.
            /// </summary>
            public NeoLoadWebMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NeoLoadWebMozillaFirefox", "/form[@title~'^NeoLoad\\ Web\\ -\\ Mozilla\\ Fir']", parentFolder, 30000, null, true, "a04d09bf-5d37-4610-9470-b86400976b0b", "")
            {
                _propertypage = new MyNeoloadTestRepositoryFolders.PropertyPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a04d09bf-5d37-4610-9470-b86400976b0b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a04d09bf-5d37-4610-9470-b86400976b0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PropertyPage folder.
            /// </summary>
            [RepositoryFolder("07730602-4f39-401e-9a8f-1e690a0a34ec")]
            public virtual MyNeoloadTestRepositoryFolders.PropertyPageFolder PropertyPage
            {
                get { return _propertypage; }
            }
        }

        /// <summary>
        /// The PropertyPageFolder folder.
        /// </summary>
        [RepositoryFolder("07730602-4f39-401e-9a8f-1e690a0a34ec")]
        public partial class PropertyPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rd1Info;
            RepoItemInfo _loginInfo;
            RepoItemInfo _linksearchInfo;

            /// <summary>
            /// Creates a new PropertyPage  folder.
            /// </summary>
            public PropertyPageFolder(RepoGenBaseFolder parentFolder) :
                    base("PropertyPage", "container[@accessiblerole='Grouping']/container[@accessiblerole='PropertyPage']", parentFolder, 30000, null, false, "07730602-4f39-401e-9a8f-1e690a0a34ec", "")
            {
                _rd1Info = new RepoItemInfo(this, "RD1", "?/?/container[@accessiblename='NeoLoad Web']/element[@accessiblename~'^This\\ content\\ is\\ announced']/form[@accessiblename='Please select an Account:']//element[@accessiblerole='None']//button[@accessiblename='R&D1']", 30000, null, "7cf62a80-c394-45d5-94e2-ab3678e78966");
                _loginInfo = new RepoItemInfo(this, "Login", "element[@accessiblerole='None']/container[@accessiblename='NeoLoad Web']/element[1]/element/element[2]/element[2]/?/?/element/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[5]/button[@accessiblename='Login']", 30000, null, "98492728-5b7d-41e8-b169-b077f60690fc");
                _linksearchInfo = new RepoItemInfo(this, "LinkSearch", "element[@accessiblerole='None']/container[@accessiblename='NeoLoad Web']/element[1]/element/element[2]/element[2]/element/element[@accessiblerole='None']/element[1]/element/element[@accessiblerole='None']/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[6]/?/?/link[@accessiblename='Search']", 30000, null, "84ccb7d4-08a8-4139-9d72-5fd167fcbb1b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07730602-4f39-401e-9a8f-1e690a0a34ec")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07730602-4f39-401e-9a8f-1e690a0a34ec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RD1 item.
            /// </summary>
            [RepositoryItem("7cf62a80-c394-45d5-94e2-ab3678e78966")]
            public virtual Ranorex.Button RD1
            {
                get
                {
                    return _rd1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RD1 item info.
            /// </summary>
            [RepositoryItemInfo("7cf62a80-c394-45d5-94e2-ab3678e78966")]
            public virtual RepoItemInfo RD1Info
            {
                get
                {
                    return _rd1Info;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("98492728-5b7d-41e8-b169-b077f60690fc")]
            public virtual Ranorex.Button Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("98492728-5b7d-41e8-b169-b077f60690fc")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The LinkSearch item.
            /// </summary>
            [RepositoryItem("84ccb7d4-08a8-4139-9d72-5fd167fcbb1b")]
            public virtual Ranorex.Link LinkSearch
            {
                get
                {
                    return _linksearchInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The LinkSearch item info.
            /// </summary>
            [RepositoryItemInfo("84ccb7d4-08a8-4139-9d72-5fd167fcbb1b")]
            public virtual RepoItemInfo LinkSearchInfo
            {
                get
                {
                    return _linksearchInfo;
                }
            }
        }

        /// <summary>
        /// The PreprodNeoloadSaasNeotysComGoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("ec25c807-4791-4b9d-8597-88f0ee3de2e2")]
        public partial class PreprodNeoloadSaasNeotysComGoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chromeInfo;

            /// <summary>
            /// Creates a new PreprodNeoloadSaasNeotysComGoogle  folder.
            /// </summary>
            public PreprodNeoloadSaasNeotysComGoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PreprodNeoloadSaasNeotysComGoogle", "/form[@title~'^preprod-neoload\\.saas\\.neot']", parentFolder, 30000, null, true, "ec25c807-4791-4b9d-8597-88f0ee3de2e2", "")
            {
                _chromeInfo = new RepoItemInfo(this, "Chrome", "container[@accessiblename='Google Chrome']/container[2]/container[2]/?/?/button[@accessiblename='Chrome']", 30000, null, "a1e2bdc5-3d4e-4c50-950e-8056c075060a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec25c807-4791-4b9d-8597-88f0ee3de2e2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec25c807-4791-4b9d-8597-88f0ee3de2e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Chrome item.
            /// </summary>
            [RepositoryItem("a1e2bdc5-3d4e-4c50-950e-8056c075060a")]
            public virtual Ranorex.Button Chrome
            {
                get
                {
                    return _chromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Chrome item info.
            /// </summary>
            [RepositoryItemInfo("a1e2bdc5-3d4e-4c50-950e-8056c075060a")]
            public virtual RepoItemInfo ChromeInfo
            {
                get
                {
                    return _chromeInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("71f36c83-b26c-44e6-8c69-ef58ed038a19")]
        public partial class ChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _parametresInfo;

            /// <summary>
            /// Creates a new Chrome  folder.
            /// </summary>
            public ChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Chrome", "/form[@title='' and @processname='chrome']", parentFolder, 30000, null, true, "71f36c83-b26c-44e6-8c69-ef58ed038a19", "")
            {
                _parametresInfo = new RepoItemInfo(this, "Parametres", "menubar[@accessiblename='']//menuitem[@accessiblename='Paramètres']", 30000, null, "be104e82-76a1-4e8e-930c-1996cc714027");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71f36c83-b26c-44e6-8c69-ef58ed038a19")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71f36c83-b26c-44e6-8c69-ef58ed038a19")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Parametres item.
            /// </summary>
            [RepositoryItem("be104e82-76a1-4e8e-930c-1996cc714027")]
            public virtual Ranorex.MenuItem Parametres
            {
                get
                {
                    return _parametresInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Parametres item info.
            /// </summary>
            [RepositoryItemInfo("be104e82-76a1-4e8e-930c-1996cc714027")]
            public virtual RepoItemInfo ParametresInfo
            {
                get
                {
                    return _parametresInfo;
                }
            }
        }

        /// <summary>
        /// The NeoLoadWebGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("aacf8add-2dd9-4682-9954-9bcf7f59afd8")]
        public partial class NeoLoadWebGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element1228856752Info;

            /// <summary>
            /// Creates a new NeoLoadWebGoogleChrome  folder.
            /// </summary>
            public NeoLoadWebGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NeoLoadWebGoogleChrome", "/form[@title~'^NeoLoad\\ Web\\ -\\ Google\\ Chro']", parentFolder, 30000, null, true, "aacf8add-2dd9-4682-9954-9bcf7f59afd8", "")
            {
                _element1228856752Info = new RepoItemInfo(this, "Element1228856752", "element[@controlid='1228856752']", 30000, null, "9f4e9a26-dc1a-4f5a-80fa-77097bd2be3f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aacf8add-2dd9-4682-9954-9bcf7f59afd8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aacf8add-2dd9-4682-9954-9bcf7f59afd8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element1228856752 item.
            /// </summary>
            [RepositoryItem("9f4e9a26-dc1a-4f5a-80fa-77097bd2be3f")]
            public virtual Ranorex.Unknown Element1228856752
            {
                get
                {
                    return _element1228856752Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1228856752 item info.
            /// </summary>
            [RepositoryItemInfo("9f4e9a26-dc1a-4f5a-80fa-77097bd2be3f")]
            public virtual RepoItemInfo Element1228856752Info
            {
                get
                {
                    return _element1228856752Info;
                }
            }
        }

    }
#pragma warning restore 0436
}